FROM ubuntu:18.04
ADD api_authentication.py /my_tests/api_authentication.py
COPY requirements.txt /tmp/
RUN apt-get update && apt-get install python3-pip -y && pip3 install -r /tmp/requirements.txt
WORKDIR /my_tests
EXPOSE 5000
ENV LOG=1
CMD python3 api_authentication.py