version: '3.8'
services:
  fastapi:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"
  authentication:
    image: authent_image:latest
    ports:
      - "5000:5000"
  authorization:
    image: author_image:latest
    ports:
      - "6000:6000"
  content:
    image: content_image:latest
    ports:
      - "7000:7000"
